import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Plus, RefreshCw, Search, UsersRound } from 'lucide-react'
import { toast } from 'sonner'
import { AppShell, PageHeader } from '@/components/portal/AppShell'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { listAccountants, createAccountant, type Accountant } from '@/lib/accountants'

export const Route = createFileRoute('/clientes/contadores')({ component: AccountantsPage, head: () => ({ meta: [{ title: 'Contadores - Clientes - Portal Prócion' }] }) })
function AccountantsPage() {
  const [rows, setRows] = useState<Accountant[]>([]); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', office: '', document: '', phone: '', email: '', notes: '' })
  const load = async () => { try { setRows(await listAccountants()) } catch (e) { toast.error(e instanceof Error ? e.message : 'Não foi possível carregar os contadores.') } }; useEffect(() => { void load() }, [])
  const filtered = rows.filter((r) => `${r.name} ${r.office ?? ''} ${r.email ?? ''}`.toLowerCase().includes(query.toLowerCase()))
  const save = async () => { if (!form.name.trim()) return toast.error('Informe o nome do contador.'); try { await createAccountant(form); toast.success('Contador cadastrado.'); setOpen(false); setForm({ name: '', office: '', document: '', phone: '', email: '', notes: '' }); await load() } catch (e) { toast.error(e instanceof Error ? e.message : 'Não foi possível cadastrar.') } }
  return <AppShell fullWidth><PageHeader title="Contadores" description="Cadastre contadores e organize os clientes vinculados." actions={<><Button variant="outline" onClick={load}><RefreshCw className="mr-2 size-4" />Atualizar</Button><Button onClick={() => setOpen(true)}><Plus className="mr-2 size-4" />Cadastrar contador</Button></>} /><div className="mb-4 relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar contador ou escritório" value={query} onChange={(e) => setQuery(e.target.value)} /></div><section className="rounded-md border bg-card"><table className="w-full text-[15px]"><thead className="border-b bg-muted/35 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Contador</th><th className="px-4 py-3">Escritório</th><th className="px-4 py-3">Contato</th><th className="px-4 py-3">Clientes</th></tr></thead><tbody className="divide-y">{filtered.map((r) => <tr key={r.id}><td className="px-4 py-3 font-semibold">{r.name}</td><td className="px-4 py-3">{r.office || '—'}</td><td className="px-4 py-3">{r.email || r.phone || '—'}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-1 text-muted-foreground"><UsersRound className="size-4" />{r.clientCount ?? 0} clientes</span></td></tr>)}</tbody></table>{!filtered.length && <div className="p-12 text-center text-muted-foreground">Nenhum contador cadastrado.</div>}</section><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Cadastrar contador</DialogTitle></DialogHeader><div className="grid gap-3"><div><Label>Nome</Label><Input className="mt-1" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div><Label>Escritório</Label><Input className="mt-1" value={form.office} onChange={(e) => setForm({ ...form, office: e.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div><Label>Telefone</Label><Input className="mt-1" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></div><div><Label>E-mail</Label><Input className="mt-1" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={save}>Salvar</Button></DialogFooter></DialogContent></Dialog></AppShell>
}

